/* Permissions file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

const permissions = {
	"category.editor": "The user can edit categories",
};

export default permissions;
